// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TanulmanyiRendszer.DAL;

namespace TanulmanyiRendszer.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200412115913_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TanulmanyiRendszer.Domain.Szemeszter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Kezdet")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TargyJelentkezesVeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TargyjelentkezesKezdet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Veg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VizsgajelentkezesKezdet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VizsgajelentkezesVeg")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Szemeszterek");
                });
#pragma warning restore 612, 618
        }
    }
}
